#!/usr/bin/env bash

# Author: GMolini

msg() {
    msg="${1:-nothing}"
    echo -e "       ${green}${msg}${nc}"
}

msg "Enable user namespace cloning"
sudo sysctl -w kernel.unprivileged_userns_clone=1

exit 0